### ISSUE TITLE
sshaudit.com: breakage

### ISSUE THREAD

**Issue by Ricky-Tigg** [uBlockOrigin/uBOL-home#116]
**v.:** 2024.2.14.104. **Tested:** Firefox

Hello. On https://www.sshaudit.com/, unlike with uBO, with this edition, _Loading, please wait..._ is exhibited instead of the intended content. This occurs regardless the operation mode selected.

**Comment by gorhill** [comment]
It's caused by the filter `/^https:\/\/www\.[a-z]{8,14}\.com\/[a-z]{1,4}\.js$/$script,3p,match-case,from=~edu|~gov,to=~exploretock.com`, because Firefox's DNR implementation does not yet support [`domainType`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/RuleCondition#domaintype) condition, see <https://bugzilla.mozilla.org/show_bug.cgi?id=1797408>.

Unfortunately, there is no workaround possible until this is implemented by Firefox.
