### ISSUE TITLE
NO hagezi support by default in ublock origin lite?

### ISSUE THREAD

**Issue by HakaishinShwet** [uBlockOrigin/uBOL-home#120]
hagezi host list is pretty awesome tbh and effective too so why not add that to default list in ublock lite?

**Comment by iam-py-test** [comment]
I assume they are referring to https://github.com/hagezi/dns-blocklists

**Comment by HakaishinShwet** [comment]
yea @iam-py-test you are right. @gorhill  its ultimate host blocklist contains much better up to date hosts for adblocking and other stuff so please check that out and please add support for hagezi ultimate list in this one

**Comment by garry-ut99** [comment]
Hagezi list is higly redundant to what uBOL built-in filters lists already block:
- 72% (44918 out of 62387) domains from Hagezi (light variant) and 
- 70% (95635 out of 136621) domains from Hagezi (normal variant) 

is already blocked / covered by uBOL built-in lists, another fact is that uBOL cannot contain too many filters due to MV3 limitations, which means best possibility would be if only unique domains would be extracted from Hagezi and added to uBOL, which means 17469 in case of Hagezi Light version or 40986 in case of Hagezi Normal.

Also worth to mention that most of hosts lists cause too many breakages compared to typical adblock filter lists which are much better quality, but on the other side all hosts lists in uBOL are disabled by default, hence users enable them only manually, on their own risk.
