### ISSUE TITLE
Can you include the filters to block Youtube endscreens?

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#127]
Youtube endscreens are really annoying. I can't include custom filters, so I can only ask you to include them.

```
##.videowall-endscreen
youtube.com##.html5-endscreen-content
youtube.com##.html5-endscreen
youtube.com##.ytp-ce-element
```

You can pack them into a filters list and set that filters list to be disabled by default.

**Comment by gradogirl** [comment]
Would be nice to be able to enable custom filters so users can customize their own internet experience. Not a lot, like 30?

How could we go about implementing this?

**Comment by iahung3** [comment]
> Would be nice to be able to enable custom filters so users can customize their own internet experience. Not a lot, like 30?
> 
> How could we go about implementing this?

From what I have read, I think it's impossible. This is the reason why I asked him to create a new filters list to include these filters.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#is-ubo-lite-a-bad-faith-attempt-at-converting-ubo-to-mv3

---

> Being entirely declarative, uBO Lite's service worker is not required to initiate DNR-, cosmetic-, or scriptlet-based filtering in a timely manner.
> 
> As a result, uBO Lite reliably filters at browser launch, or when navigating to new webpages while its service worker is suspended. This can't be achieved without uBO Lite's declarative approach.

---

> Non-declarative MV3-based content blockers will suffer unreliable filtering when their service worker has been suspended, since waking up a service worker requires a lot of initialization work and delays time-critical filtering abilities. Such content blocker may end up using trickery to force their service worker to always be up and running.

**Comment by garry-ut99** [comment]
> > gradogirl : Would be nice to be able to enable custom filters so users can customize their own internet experience. Not a lot, like 30?
>
> temp-account-commits : This has already been questioned by another user before in the discussion https://github.com/uBlockOrigin/uBOL-home/discussions/37, and @ gorhill decided that he will intentionally not add this option, despite it being possible.

Also in many other duplicates. gradogirl's feature request is another duplicate of a pile of duplicates:
- https://github.com/uBlockOrigin/uBOL-home/issues/17
- https://github.com/uBlockOrigin/uBOL-home/discussions/37
- https://github.com/uBlockOrigin/uBOL-home/issues/36
- https://github.com/uBlockOrigin/uBOL-home/discussions/60
- https://github.com/uBlockOrigin/uBOL-home/issues/125
- https://github.com/uBlockOrigin/uBOL-home/issues/134

<hr>

> > gradogirl : Would be nice to be able to enable custom filters so users can customize their own internet experience. Not a lot, like 30? How could we go about implementing this?
> 
> temp-account-commits : From what I have read, I think it's impossible. This is the reason why I asked him to create a new filters list to include these filters.

Yes, he asked it in his previous thread: 
- https://github.com/uBlockOrigin/uBOL-home/issues/125 

which is one of duplicates listed above.

You both created duplicates, try to not spam issue tracker with duplicates, read FAQ and search for previous issues before reporting a new issue. The current uBOL issue tracker has not many issues anf FAQ is not big, which means it's hard to miss anything, but you still missed them, which means that most likely you didn't even read FAQ nor searched for previous issues, because you were too lazy, laziness is not welcomed here.

<hr>

> iahung3: Can you include the filters to block Youtube endscreens? Youtube endscreens are really annoying. I can't include custom filters, so I can only ask you to include them.

Wrong repository to report filters, uBOL uses filters lists converted from uBlock Origin, uBOL filter requests are to be reported to Ublock Origin filters repositories:
- https://github.com/easylist/easylist
- https://github.com/uBlockOrigin/uAssets
- https://github.com/AdguardTeam/AdguardFilters

I don't know which "Youtube endscreens" do you exactly mean, and what kind of elements they are, because you didn't provide any screenshoots, but I don't see your nickname reporting anything to these repositories, there is a possibility that if you report "Youtube endscreens" to them, they might be accepted and fixed in uBlock Origin filter lists, and then perhaps copied to uBOL filter lists. Try it first before reporting filtes to uBOL. Unless devs already declined to fix "Youtube endscreens" in the past, and that's why you came here, in that case, perhaps they can be reported and fixed in:
- https://github.com/AdguardTeam/AdguardFilters

and then you can continue here:
- https://github.com/uBlockOrigin/uBOL-home/discussions/137

**Comment by iahung3** [comment]
What a waste of time! I'm not here for you to lecture me. I want something that could work for me. Regarding the FAQ, I don't necessarily agree with your decisions, and I might want to start discussions to persuade you to change them. It's my right, and it's definitely not because I'm lazy or intentionally want to spam. Otherwise, you should add to that FAQ that the design decisions here are sorted out once and forever, and no further discussions are allowed. I know your answer will be to fork it and do whatever I want. I don't have the ability to do that, so I will find other solutions like Brave or Adguard MV3. Goodbye.

**Comment by garry-ut99** [comment]
> iahung3 : What a waste of time! I'm not here for you to lecture me.

Waste of time is when volunteers have to reply and handle duplicated issues / questions that generate clutter, over and over, if you and gradogirl wouldn't spam, you wouldn't be lectured. 

> iahung3 : and it's definitely not because I'm lazy or intentionally want to spam.

You're denying laziness as the reason, and at the same time you're avoiding to provide what the true reason was.
Then for what other reason than laziness, did you and gradogirl overlook 5 other same duplicate threads on such a small issue tracker that has only ~130 discussions/issues, a small FAQ, and has a great search functionality? I guess one has to be blind to overlook all of them at once, so unless you provide a reasonable reason, not just denying, the laziness still holds as the reason. Just don't say you didn't have time or that you were in a hurry, because developers also don't have time to handle and respond to duplicate problems/questions, you can't save time at the expense of other people's time, other people's time is not less important than your time.

> iahung3 : Regarding the FAQ, I don't necessarily agree with your decisions, and I might want to start discussions to persuade you to change them. It's my right, Otherwise, you should add to that FAQ that the design decisions here are sorted out once and forever, and no further discussions are allowed. I know your answer will be to fork it and do whatever I want. I don't have the ability to do that, so I will find other solutions like Brave or Adguard MV3. Goodbye.

When I said about duplicates, I meant your previous issue, not the current one, as the current one is a bit different, I have nothing against discussing the current issue, so you don't need to close it so quickly, if you want to discuss it further. Also, maybe you confused me with the uBO creator, I'm a free volunteer, not the uBO creator, hence my opinions are not final decisions of the creator, nor I created the FAQ or made design chocies.

**Comment by gradogirl** [comment]
This is going to sound rude: but I don't like being labelled as lazy or spamming. I am new to github and failed to search closed issues, I apologize. I do enjoy reading the FAQ and wiki. Hope you understand.

On chrome, the custom filters I like using on uBlock Origin are:
! disables Cast SDK: https://developers.google.com/cast/docs/chrome_sender/integrate
||gstatic.com/cv/js/sender/v1/cast_sender.js^

Youtube endscreen refers to: https://www.reddit.com/r/uBlockOrigin/wiki/solutions/youtube/#wiki_video_annotations

! [reddit.com/r/uBlockOrigin/comments/tcswua/tip_noncosmetic_filters_to_remove_junk_from/](https://www.reddit.com/r/uBlockOrigin/comments/tcswua/tip_noncosmetic_filters_to_remove_junk_from/) 
||youtube.com/*/annotations_module.js
||youtube.com/*/endscreen.js

How should I proceed: where would you suggest I go next?

**Comment by freezer2022** [comment]
> gradogirl:  I am new to github and failed to search closed issues.

I'm curious what exactly was the problem you had with using github, because your answer doesn't explain anything, and looks like a desperate attempt to find a cheap excuse after being caught red-handed. I don't understand how being "a new to github" prevents you from using a simple search functionality or prevents you from scrolling manually a small ammout of issues/discussions's titles, github is not different to a typical forum: before creating a new issue/comment, an user have to check for old issues by using a search functionality or by scrolling trough old threads's titles. It seems you both (altogether with the iahung3) can't handle a simple fact you got caught red-handed and lectured, and now you cry because you lack a real argument to justify.

> gradogirl: How should I proceed: where would you suggest I go next?

Ammout of filters being requested by community to be included in uBOL due to uBOL lacking "My filters" feature, will be much bigger and will grow by time, day by day, week by week, month by month

The only solution I see, other than declining the issue permanently as "won't fix" or than implementing "My filters" in uBOL, is to create a filter list in uBOL whose purpose will be to include such filters

Such filter list would be maintained at uAssets and could be named something like: "uBOL supplementary filters" or uBOL community filters".

But there is one problem, last request to create additional new "Dark mode" filter list in uBO: https://github.com/uBlockOrigin/uBlock-issues/discussions/3262 has ended as permanently declined by one of devs followed by the uBO creator, with a reason that most devs are already busy too much to maintain another filter list, hence I don't know who is going to maintain "uBOL supplementary" filter list, maybe the community.
