### ISSUE TITLE
noFiltering Admin Policy not working

### ISSUE THREAD

**Issue by pyther** [uBlockOrigin/uBOL-home#174]
I've declared the following configuration profile on macOS
```
com.google.Chrome.extensions.ddkjiahejlhfcafbddmgiahcphecmpfh
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>disableFirstRunPage</key>
	<true/>
	<key>noFiltering</key>
	<array>
		<string>grubhub.com</string>
		<string>google.com</string>
		<string>youtube.com</string>
	</array>
</dict>
</plist>
```

Chrome detects the settings, as seen via chrome://policy
<img width="1557" alt="image" src="https://github.com/user-attachments/assets/52240964-f5fc-43d1-a9ac-f55d157f5ac7">

The filter list is empty in the extension settings:
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/560847d0-9684-40c8-bf4c-a140cf5fc2d3">

Adblocking is not disable for for grubhub, google.com, or youtube.com. 
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/4fd730b6-34f8-4096-b6a9-394abdc8b31b">

Chrome: 127.0.6533.100
uBlock Origin Lite 2024.8.5.925
macOS: 14.6.1

I'm not sure what other information would be helpful, but happy to provide anything needed.

**Comment by gorhill** [comment]
Did you try restarting the browser more than once?

**Comment by pyther** [comment]
Thanks, restarting twice did the trick. However, I noticed that sites that are removed from the `noFiltering` array are not removed from the No Filtering list. For example if I set `noFiltering = ['google.com', 'facebook.com']` then change the array to `noFiltering = ['youtube.com', 'grubhub.com']` all four domains are included in the plugin's No Filtering list. Is this expected behavior?

**Comment by gorhill** [comment]
> Is this expected behavior?

Yes, the hostnames from `noFiltering` do not overwrite the existing ones.

**Comment by Dacatzgoescodin5267** [comment]
Make the damn thing work with mv3 and not forcing me to use the shitty Lite version nor switching browsers

**Comment by trogau** [comment]
Apologies if this is conflating two issues - I'm not sure how much of the extension stuff is platform specific and how much of it is inherent to the extension - but I'm trying to get the noFiltering policy deployed via Google Workspace. 

I've done this successfully with uBO previously, with a Policy for extensions like: 

`{  "toAdd": {  "Value" : { "trustedSiteDirectives": [ "example.org" ] } } }`

.. defined in Google Workspace, using `toAdd` or `toOverwrite`. 

Based on comments here I assumed it might be `noFiltering` instead of `trustedSiteDirectives`, but that doesn't seem to work (I tested `trustedSiteDirectives` as well), even after multiple Chrome restarts / reboots. 

Do I simply have the wrong Value field here, or does uBOL not have this functionality at this point in time?

Thanks!

**Comment by cgerke** [comment]
> > Is this expected behavior?
> 
> Yes, the hostnames from `noFiltering` do not overwrite the existing ones.

Planning to implement later?

**Comment by gorhill** [comment]
While working on <https://github.com/gorhill/uBlock/commit/15dae359f7e9e75c49a86bad8a05ec3f7add3c35>, I found out that there is a long delay at launch when reading policy settings through [`storage.managed.get()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed), on the order of 7-10 seconds on my side.

I revisited the policy-related code so that it can apply the policy settings in a deferred manner once they become available. Hopefully the issue here will benefit the change -- there should no longer a need to restart although the first time a policy is modified it might take seconds for it to become available to uBO. After this first time, uBO cache the policy in its more reliable storage so that it's available immediately at launch time.

**Comment by gorhill** [comment]
> sites that are removed from the noFiltering array are not removed from the No Filtering list

Additionally, in the commit I added support for `-*`, which purpose is to remove all existing hostnames from the no-filtering list. Use this to start from a clean slate. Specific hostname can also be removed by prepending them with `-`, e.g. `-example.com` will remove `example.com` from the no-filtering list.
