### ISSUE TITLE
Display issue in chrome ?

### ISSUE THREAD

**Issue by coooly** [uBlockOrigin/uBOL-home#189]
Hello,

i'm presetting some excluded url for my company for Edge and Chrome.

While edge are displaying them correctly as set like "*.myurl.com", Chrome ubol setting page is displaying %2A.myurl.com.

Is it normal ? Will exclusion be applied anyway ? 

![image](https://github.com/user-attachments/assets/8cf294f8-1103-45c0-920e-e57a0d09f429)

Chrome: 128.0.6613.85 
UBOL : 2024.8.21.996

Thank you !

**Comment by garry-ut99** [comment]
> Is it normal ? Will exclusion be applied anyway ?

Both `*.myurl.com` and `%2A.myurl.com` will not work: in Firefox such filter is rejected as invalid, in Chromium-based browsers it's accepted but `*` is encoded to `%2A` and doesn't work, perhaps it's a bug or some incompatibility and such a filter should be rejected in Chromium as invalid, just like in Firefox case.

Besides, `myurl.com` is sufficient because it will work also for all the subdomains, hence  `*.` is unnecessary and redundant. Unless you wanted to whitelist only subdomains of `myurl.com` but not `myurl.com` itself.


> While edge are displaying them correctly as set like `*.myurl.com`, Chrome ubol setting page is displaying `%2A.myurl.com`.

It's initially displayed as `*.myurl.com` in all Chromium-browsers, but it's not saved yet, to be saved an user needs to interact with dashboard somewhere outside text input area (click some checkbox or switch filter mode, or reload dashboard page), once interacted it will be saved and become `%2A.myurl.com`, most likely you didn't interact in Edge, hence it was still displayed as unsaved `*.myurl.com`.

**Comment by coooly** [comment]
Thanks Gary. I didn't know that it applies to subdomains as well. 

I'll correct it in my powershell script.

**Comment by garry-ut99** [comment]
> coooly: I didn't know that it applied to subdomains as well.

It's already answered, duplicate of:
- https://github.com/uBlockOrigin/uBOL-home/discussions/148
