### ISSUE TITLE
High number of blocked requests cut off by Chrome UI

### ISSUE THREAD

**Issue by aheckler** [uBlockOrigin/uBOL-home#193]
If you have a very large number of blocked requests (in a tab that's been open for a long time, say) the counter will be cut off by the Chrome UI in the toolbar. Example screenshot:

![Screenshot taken on 2024-08-26 at 22 45 21 UTC@2x](https://github.com/user-attachments/assets/1d443cb8-614e-43c4-9eff-52c45d7a6d51)

Perhaps after 1000 blocked requests it should abbreviate the number as 1k, then 2k, 3k, etc.? Surely the _exact_ number of blocked requests is not important at that point?

Of course, this is just a minor interface niggle, nothing critical. :) Thanks for your hard work on uBOL and uBO!

**Comment by gorhill** [comment]
The badge is under the control of the browser, report to browser devs.

**Comment by garry-ut99** [comment]
By the way (1): until it will be addressed by Chrome devs, currently as the alternative/workaround, it's possible to disable the badge counter in uBOL (of course it's only for users who can live without badge counter):

- https://github.com/uBlockOrigin/uBOL-home/discussions/63
- https://github.com/uBlockOrigin/uBOL-home/issues/119


<hr>

By the way (2):
> Perhaps after 1000 blocked requests it should abbreviate the number as 1k, then 2k, 3k, etc.? Surely the exact number of blocked requests is not important at that point?

that's the default behavior in uBO (MV2) since the beginning:
- https://github.com/gorhill/uBlock/issues/392
- https://github.com/uBlock-LLC/uBlock/issues/1681
