### ISSUE TITLE
Ad placeholder in optimal mode

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uBOL-home#99]
In https://scroll.in/latest/1060756/new-telecom-bill-will-allow-centre-to-take-over-suspend-services-for-national-security , https://indianexpress.com/ , There is ad placeholder when optimal mode is enabled in ublock origin lite, but is hidden in full mode, uBO
![image](https://github.com/uBlockOrigin/uBOL-home/assets/111110599/34ad6f5f-f2cc-4de1-9baa-d8d676f8bb14)
![image](https://github.com/uBlockOrigin/uBOL-home/assets/111110599/ffb0dbb9-b32b-4f41-bfed-f2905a5139ac)

**Comment by gorhill** [comment]
Use Complete mode when Optimal is not enough.

**Comment by libreom** [comment]
Cosmetic filters not present in optimal mode? Just asking what's the difference between optimal mode and full mode?
Also even in full mode, placeholder is visible for a split second and then disappears in these websites

**Comment by gorhill** [comment]
It's explained in the dashboard.

Optimal:

> Advanced network filtering plus specific extended filtering from selected filter lists.

Complete:

> Advanced network filtering plus specific and generic extended filtering from selected filter lists.

Specific cosmetic filtering is enabled with Optimal. Generic cosmetic filtering is enabled with Complete.

**Comment by gorhill** [comment]
> Also even in full mode, placeholder is visible for a split second

I don't see this, it might depend how many lists you selected, how many extensions you have enabled, and how performant is your computer. Is it with Firefox or Chromium? I do know that MV3 results with  Firefox are not as good than with Chromium.

> does uBOL something different here

uBO will cache and apply sooner generic cosmetic filters which were found in previous page load. This is not possible with uBOL since they are applied declaratively, and they are applied declaratively because the service worker can become inactive at any time.

**Comment by libreom** [comment]
I am using chrome with weak pc-4gb ram, old cpu, it is only for a split second tho, but not in uBO

**Comment by gorhill** [comment]
For `indianexpress.com` the required specific filter is `indianexpress.com##.adsbox970x90`. For `scroll.in`, the required specific filter is `scroll.in##.below-navigation-banner-wrapper`.

You could ask <https://github.com/mediumkreation/IndianList> to add these specific cosmetic filters so that next uBOL version the placeholder are hidden with Optimal mode.
